---
- name: Ansible rest and tags
  hosts: localhost
  gather_facts: no

  vars:
    myrsakey: "{{lookup('file', '/home/student/.ssh/id_rsa.pub') }}"
    astros: "{{ lookup('url', 'http://api.open-notify.org/astros.json') }}"
  tasks:
    - name: Key prep
      debug:
        msg: "Your RSA key is {{ myrsakey }}"
      tags:
        - keytime
        - vmprep

    - name: show astros and cosmos on the ISS
      debug:
        msg: "Today on the ISS are: {{ astros.people }}" 
      tags:
        - jsonwork 
        - astros 

    - name: clean up the ISS data
      debug:
        msg: "Let me format that data with a loop: {{ item }}"      
      loop: "{{ astros.people|map(attribute='name')|list }}"
      tags:
        - astros 

    - name: pretend playbook takes a long time to run
      pause:
        seconds: 100

    - name: "The task I'm currently working on "
       
